apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: hdo6i8gaq-python
  janus-idp.io/tekton: hdo6i8gaq-python
  backstage.io/kubernetes-id: hdo6i8gaq-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: hdo6i8gaq-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
